### ISSUE TITLE
feat: customize variable qualities

### ISSUE THREAD

**Issue by sherwinski** [imgix/imgix-python#100]
# Description

> Related to https://github.com/imgix/js-core#variable-qualities

Add a `variable_qualities` option to the https://github.com/imgix/imgix-python#fixed-width-images function to allow users to override the mapping of the quality parameter (`q`) to each device pixel ratio (`dpr`). This will allow users to have more granular control over the fixed-size srcset values generated.

**Comment by ashutoshkrris** [comment]
Hi @sherwinski 
I'd like to try this issue.

**Comment by sherwinski** [comment]
Hey @ashutoshkrris and thanks for your interest 👋
I'll go ahead and assign this issue to you now and please feel free to ping me or anyone in @imgix/imgix-sdk-team if you have any questions.
