### ISSUE TITLE
feat: optionally disable path encoding

### ISSUE THREAD

**Issue by luqven** [imgix/imgix-python#91]
## Description
> Related PR: https://github.com/imgix/js-core/pull/314

Add `disablePathEncoding` functionality to the URL building logic in [`create_url`](https://github.com/imgix/imgix-python/blob/bbb5986dc627626811d2283ab9e273e46c9dbeb7/imgix/urlbuilder.py#L92-L122) and [`create_srcset`](https://github.com/imgix/imgix-python/blob/bbb5986dc627626811d2283ab9e273e46c9dbeb7/imgix/urlbuilder.py#L180-L266). This way, users can decide to opt-out of path encoding.

Probably a good way of handling this would be to add a new constructor option, `disablePathEncoding`, that can be referenced in any of the instance methods.

**Comment by luqven** [comment]
Hey @ashutoshkrris 👋 ,

Glad to hear it! I'll marked this issue as assigned to you.

In terms of next steps, please either comment here or open a RFC (request for comment) draft PR explaining the change you'd like to implement. 

You can also take a look at our contributing guidelines to get you started.

If you have any trouble at all getting setup or have any questions, don't hesitate to comment here and tag a team member.

**Comment by ashutoshkrris** [comment]
Thanks for assigning me the issue, @luqven.
Just to confirm, we have these conditions:

* If `disablePathEncoding` is set to `True`, then `http://www.example.com/products/123` will have no change.
* If `disablePathEncoding` is set to `False`, then `http://www.example.com/products/123` will be converted to `http://www.example.com/products%2F123`.

Is what I understand correct?

**Comment by luqven** [comment]
Hey @ashutoshkrris, apologies for the confusion I'll try and make the task a little clearer.

If `disablePathEncoding` is set to `true` then the parts of the path that do not adhere to the [URL spec](https://url.spec.whatwg.org/#valid-url-string) should _not_ be encoded. 

For example:

**When `disablePathEncoding` is set to `false`, IE the default behavior**
- [http://sdk-test.imgix.net/ <>[]{}|\^%.jpg](http://sdk-test.imgix.net/%20%3C%3E[]%7B%7D%7C/%5E%.jpg)  → [http://sdk-test.imgix.net/%20%3C%3E[]%7B%7D%7C/%5E%.jpg](http://sdk-test.imgix.net/%20%3C%3E[]%7B%7D%7C/%5E%.jpg)
- http://www.example.com/products/123 → http://www.example.com/products/123

**When `disablePathEncoding` is set to `true`**
- [http://sdk-test.imgix.net/ <>[]{}|\^%.jpg](http://sdk-test.imgix.net/%20%3C%3E[]%7B%7D%7C/%5E%.jpg) → [http://sdk-test.imgix.net/ <>[]{}|\^%.jpg](http://sdk-test.imgix.net/%20%3C%3E[]%7B%7D%7C/%5E%.jpg) 
- http://www.example.com/products/123 → http://www.example.com/products/123


As a suggestion, you could do some test-driven development ([TDD](http://butunclebob.com/ArticleS.UncleBob.TheThreeRulesOfTdd)) here by creating a variant of these [tests](https://github.com/imgix/imgix-python/blob/85bdef1dd299a102d91b322260a383d1cd2d4bfc/tests/test_url_builder.py#L129-L147). They should test that settings `disablePathEncoding` esnures the URL _does not_ get encoded.

To run those tests, in the project root you'll need to run:
- `pip install ".[test]"`
- `pip install tox`
- `tox`

**Comment by ashutoshkrris** [comment]
@luqven 
In order to add the optional `disable_path_encoding` functionality, I'd like to make the following changes:

1. Add `_disable_path_encoding` in the constructor of `UrlBuilder` class with a default value of `False`.
2. Update the `_sanitize_path` method to use the `_disable_path_encoding` variable.
3. Add more testcases in `test_url_builder` and `test_srcset` to cover the new scenarios.

Let me know if I am missing something.
